In [1]:
import pandas as pd
import numpy as np

In [2]:
selloutData = pd.read_csv("../dataset/kopo_channel_seasonality_new.csv")

In [3]:
### 1. 데이터 타입 통합 
### 2. 불량 데이터 처리

### 1.데이터 타입 통합

In [4]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
dtype: object

In [5]:
selloutData["YEARWEEK"] = selloutData.YEARWEEK.astype("str")

In [6]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK     object
QTY         float64
dtype: object

### 2. 불량 데이터 처리

In [7]:
selloutData.min()

REGIONID         A00
PRODUCT     PRODUCT1
YEARWEEK      201401
QTY             -364
dtype: object

### 행/열 조회

In [8]:
selloutData[selloutData.QTY < 0].head() #변수에 담지 않았으므로 조회만 한 것

     REGIONID    PRODUCT YEARWEEK   QTY
65        A02  PRODUCT16   201403  -1.0
338       A08  PRODUCT36   201402  -1.0
1270      A14  PRODUCT36   201405  -1.0
1616      A17  PRODUCT60   201402  -1.0
2035      A39   PRODUCT7   201404 -12.0

In [9]:
len(selloutData[selloutData.QTY < 0]) #변수에 담지 않았으므로 조회만 한 것- 길이 조회

323

### 3. 데이터 정제

In [10]:
selloutData2 = np.where(selloutData.QTY < 0 , 0 , selloutData.QTY)

In [11]:
selloutData2 #특정 컬럼을 지정하지 않으면 배열로 출력

array([   71., 22275.,  4463., ...,     0., 15021.,   568.])

In [12]:
#selloutData["QTY"] = np.where(selloutData.QTY < 0, 0, selloutData.QTY)  ##

In [13]:
#selloutData #특정 컬럼을 지정하여 조건을 부여하면 데이터프레임으로 출력/ 근데 얘는 원자료 변화 로그 남기기 힘듦

In [14]:
selloutData["new_QTY"] = np.where(selloutData.QTY < 0, 0, selloutData.QTY)

In [15]:
selloutData #이렇게 해서 비교되게 해줘야해

       REGIONID    PRODUCT YEARWEEK       QTY   new_QTY
0           A60   PRODUCT4   201402      71.0      71.0
1           A60  PRODUCT59   201402   22275.0   22275.0
2           A60  PRODUCT34   201402    4463.0    4463.0
3           A60  PRODUCT47   201402       0.0       0.0
4           A60  PRODUCT56   201402      23.0      23.0
5           A60  PRODUCT57   201402      14.0      14.0
6           A60  PRODUCT12   201402    1186.0    1186.0
7           A60   PRODUCT1   201402       7.0       7.0
8           A60  PRODUCT33   201402     101.0     101.0
9           A60  PRODUCT62   201402     336.0     336.0
10          A37  PRODUCT58   201402       0.0       0.0
11          A37  PRODUCT59   201402   11492.0   11492.0
12          A37  PRODUCT34   201402     825.0     825.0
13          A31  PRODUCT58   201402       0.0       0.0
14          A31  PRODUCT59   201402     560.0     560.0
15          A31  PRODUCT34   201402     103.0     103.0
16          A04  PRODUCT58   201402       0.0       0.0
17          A04  PRODUCT63   201402     740.0     740.0
18          A04  PRODUCT15   201402     394.0     394.0
19          A04   PRODUCT4   201402    2550.0    2550.0
20          A04  PRODUCT16   201402       4.0       4.0
21          A04  PRODUCT59   201402   36549.0   36549.0
22          A04  PRODUCT34   201402    4773.0    4773.0
23          A04  PRODUCT40   201402     146.0     146.0
24          A04  PRODUCT47   201402       5.0       5.0
25          A04  PRODUCT60   201402       9.0       9.0
26          A04  PRODUCT56   201402     109.0     109.0
27          A04  PRODUCT57   201402    1195.0    1195.0
28          A04  PRODUCT12   201402   15028.0   15028.0
29          A04   PRODUCT1   201402    1319.0    1319.0
...         ...        ...      ...       ...       ...
124628      A16  PRODUCT64   201630     188.0     188.0
124629      A16  PRODUCT48   201630      16.0      16.0
124630      A16  PRODUCT49   201630       9.0       9.0
124631      A16  PRODUCT74   201630      18.0      18.0
124632      A16  PRODUCT40   201630     285.0     285.0
124633      A16  PRODUCT47   201630     155.0     155.0
124634      A16  PRODUCT60   201630    2491.0    2491.0
124635      A16  PRODUCT56   201630    2026.0    2026.0
124636      A16  PRODUCT12   201630   17067.0   17067.0
124637      A16   PRODUCT1   201630     168.0     168.0
124638      A16  PRODUCT41   201630       0.0       0.0
124639      A16  PRODUCT51   201630       0.0       0.0
124640      A16  PRODUCT68   201630       0.0       0.0
124641      A16  PRODUCT33   201630    3887.0    3887.0
124642      A16  PRODUCT14   201630      95.0      95.0
124643      A10   PRODUCT2   201630   12570.0   12570.0
124644      A10  PRODUCT58   201630    4461.0    4461.0
124645      A10  PRODUCT63   201630    4308.0    4308.0
124646      A10  PRODUCT15   201630       0.0       0.0
124647      A10   PRODUCT4   201630    3012.0    3012.0
124648      A10  PRODUCT16   201630     231.0     231.0
124649      A10  PRODUCT59   201630  231024.0  231024.0
124650      A10  PRODUCT34   201630   34436.0   34436.0
124651      A10  PRODUCT40   201630       0.0       0.0
124652      A10  PRODUCT47   201630       4.0       4.0
124653      A10  PRODUCT60   201630     824.0     824.0
124654      A10  PRODUCT56   201630     275.0     275.0
124655      A10  PRODUCT61   201630       0.0       0.0
124656      A10  PRODUCT12   201630   15021.0   15021.0
124657      A10   PRODUCT1   201630     568.0     568.0

[124658 rows x 5 columns]

In [16]:
len(selloutData) #원자료와 처리한 자료가 동일한지 확인하는 작업 필요

124658

In [17]:
len(selloutData[selloutData.QTY  >= 0][selloutData.QTY == selloutData.new_QTY])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

124335

In [18]:
#연주차 분리하여 컬럼 생성
selloutData['YAER'] = selloutData.YEARWEEK.str[0:4]
selloutData['WEEK'] = selloutData.YEARWEEK.str[4:6]

In [19]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK     object
QTY         float64
new_QTY     float64
YAER         object
WEEK         object
dtype: object

In [20]:
selloutData.head()

  REGIONID    PRODUCT YEARWEEK      QTY  new_QTY  YAER WEEK
0      A60   PRODUCT4   201402     71.0     71.0  2014   02
1      A60  PRODUCT59   201402  22275.0  22275.0  2014   02
2      A60  PRODUCT34   201402   4463.0   4463.0  2014   02
3      A60  PRODUCT47   201402      0.0      0.0  2014   02
4      A60  PRODUCT56   201402     23.0     23.0  2014   02

In [21]:
#selloutData 의 53주차 제거

In [22]:
selloutData.WEEK.astype(int) > 53

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
124628    False
124629    False
124630    False
124631    False
124632    False
124633    False
124634    False
124635    False
124636    False
124637    False
124638    False
124639    False
124640    False
124641    False
124642    False
124643    False
124644    False
124645    False
124646    False
124647    False
124648    False
124649    False
124650    False
124651    False
124652    False
124653    False
124654    False
124655    False
124656    False
124657    False
Name: WEEK, Length: 124658, dtype: bool

In [23]:
selloutData[selloutData.WEEK.astype(int) <= 53] #df명[df명.컬럼명 + 조건] 으로 써야 df 형태로 조회됨

       REGIONID    PRODUCT YEARWEEK       QTY   new_QTY  YAER WEEK
0           A60   PRODUCT4   201402      71.0      71.0  2014   02
1           A60  PRODUCT59   201402   22275.0   22275.0  2014   02
2           A60  PRODUCT34   201402    4463.0    4463.0  2014   02
3           A60  PRODUCT47   201402       0.0       0.0  2014   02
4           A60  PRODUCT56   201402      23.0      23.0  2014   02
5           A60  PRODUCT57   201402      14.0      14.0  2014   02
6           A60  PRODUCT12   201402    1186.0    1186.0  2014   02
7           A60   PRODUCT1   201402       7.0       7.0  2014   02
8           A60  PRODUCT33   201402     101.0     101.0  2014   02
9           A60  PRODUCT62   201402     336.0     336.0  2014   02
10          A37  PRODUCT58   201402       0.0       0.0  2014   02
11          A37  PRODUCT59   201402   11492.0   11492.0  2014   02
12          A37  PRODUCT34   201402     825.0     825.0  2014   02
13          A31  PRODUCT58   201402       0.0       0.0  2014   02
14          A31  PRODUCT59   201402     560.0     560.0  2014   02
15          A31  PRODUCT34   201402     103.0     103.0  2014   02
16          A04  PRODUCT58   201402       0.0       0.0  2014   02
17          A04  PRODUCT63   201402     740.0     740.0  2014   02
18          A04  PRODUCT15   201402     394.0     394.0  2014   02
19          A04   PRODUCT4   201402    2550.0    2550.0  2014   02
20          A04  PRODUCT16   201402       4.0       4.0  2014   02
21          A04  PRODUCT59   201402   36549.0   36549.0  2014   02
22          A04  PRODUCT34   201402    4773.0    4773.0  2014   02
23          A04  PRODUCT40   201402     146.0     146.0  2014   02
24          A04  PRODUCT47   201402       5.0       5.0  2014   02
25          A04  PRODUCT60   201402       9.0       9.0  2014   02
26          A04  PRODUCT56   201402     109.0     109.0  2014   02
27          A04  PRODUCT57   201402    1195.0    1195.0  2014   02
28          A04  PRODUCT12   201402   15028.0   15028.0  2014   02
29          A04   PRODUCT1   201402    1319.0    1319.0  2014   02
...         ...        ...      ...       ...       ...   ...  ...
124628      A16  PRODUCT64   201630     188.0     188.0  2016   30
124629      A16  PRODUCT48   201630      16.0      16.0  2016   30
124630      A16  PRODUCT49   201630       9.0       9.0  2016   30
124631      A16  PRODUCT74   201630      18.0      18.0  2016   30
124632      A16  PRODUCT40   201630     285.0     285.0  2016   30
124633      A16  PRODUCT47   201630     155.0     155.0  2016   30
124634      A16  PRODUCT60   201630    2491.0    2491.0  2016   30
124635      A16  PRODUCT56   201630    2026.0    2026.0  2016   30
124636      A16  PRODUCT12   201630   17067.0   17067.0  2016   30
124637      A16   PRODUCT1   201630     168.0     168.0  2016   30
124638      A16  PRODUCT41   201630       0.0       0.0  2016   30
124639      A16  PRODUCT51   201630       0.0       0.0  2016   30
124640      A16  PRODUCT68   201630       0.0       0.0  2016   30
124641      A16  PRODUCT33   201630    3887.0    3887.0  2016   30
124642      A16  PRODUCT14   201630      95.0      95.0  2016   30
124643      A10   PRODUCT2   201630   12570.0   12570.0  2016   30
124644      A10  PRODUCT58   201630    4461.0    4461.0  2016   30
124645      A10  PRODUCT63   201630    4308.0    4308.0  2016   30
124646      A10  PRODUCT15   201630       0.0       0.0  2016   30
124647      A10   PRODUCT4   201630    3012.0    3012.0  2016   30
124648      A10  PRODUCT16   201630     231.0     231.0  2016   30
124649      A10  PRODUCT59   201630  231024.0  231024.0  2016   30
124650      A10  PRODUCT34   201630   34436.0   34436.0  2016   30
124651      A10  PRODUCT40   201630       0.0       0.0  2016   30
124652      A10  PRODUCT47   201630       4.0       4.0  2016   30
124653      A10  PRODUCT60   201630     824.0     824.0  2016   30
124654      A10  PRODUCT56   201630     275.0     275.0  2016   30
124655      A10  PRODUCT61   201630       0.0       0.0  2016   30
124656      A10  PRODUCT12   201630   15021.0   15021.0  2016   30
124657      A10   PRODUCT1   201630     568.0     568.0  2016   30

[124658 rows x 7 columns]

In [24]:
refinedSelloutData = selloutData[selloutData.WEEK.astype(int) <= 53]

In [25]:
refinedSelloutData.head()

  REGIONID    PRODUCT YEARWEEK      QTY  new_QTY  YAER WEEK
0      A60   PRODUCT4   201402     71.0     71.0  2014   02
1      A60  PRODUCT59   201402  22275.0  22275.0  2014   02
2      A60  PRODUCT34   201402   4463.0   4463.0  2014   02
3      A60  PRODUCT47   201402      0.0      0.0  2014   02
4      A60  PRODUCT56   201402     23.0     23.0  2014   02

In [26]:
len(refinedSelloutData)

124658

In [27]:
len(refinedSelloutData[refinedSelloutData.WEEK.astype(int) > 53])

0

### 데이터 정렬

In [28]:
sortKey = ['REGIONID', 'PRODUCT', 'YEARWEEK']

In [29]:
sortedData = refinedSelloutData.sort_values(sortKey)

In [30]:
sortedData.head()

     REGIONID    PRODUCT YEARWEEK    QTY  new_QTY  YAER WEEK
298       A00  PRODUCT34   201401  661.0    661.0  2014   01
1757      A00  PRODUCT34   201402  679.0    679.0  2014   02
3125      A00  PRODUCT34   201403  578.0    578.0  2014   03
205       A00  PRODUCT34   201404  532.0    532.0  2014   04
4369      A00  PRODUCT34   201405  516.0    516.0  2014   05

### 데이터 집계(Group By)

In [31]:
groupKey = ['REGIONID', 'PRODUCT']

In [32]:
gFunction = ['mean' , 'std']

In [33]:
groupData = sortedData.groupby(groupKey).agg(gFunction)

In [34]:
groupData

                              QTY                       new_QTY
                             mean            std           mean            std
REGIONID PRODUCT
A00      PRODUCT34     132.445860     154.867743     132.445860     154.867743
         PRODUCT58     105.235669     273.435108     105.235669     273.435108
         PRODUCT59   36086.547771   15192.174914   36086.547771   15192.174914
A01      PRODUCT1     5716.726115    3704.948589    5716.726115    3704.948589
         PRODUCT12  197052.777070  198866.717131  197052.777070  198866.717131
         PRODUCT14   17934.738854    9402.640836   17934.738854    9402.640836
         PRODUCT15    4759.554140    1528.260828    4759.554140    1528.260828
         PRODUCT16    1392.394904     734.344988    1392.394904     734.344988
         PRODUCT19    3335.140127     996.017547    3335.140127     996.017547
         PRODUCT2    22769.891720   23307.183239   22769.891720   23307.183239
         PRODUCT20      62.955414      76.027605      63.254777      75.729859
         PRODUCT33   11919.828025    6300.941637   11919.828025    6300.941637
         PRODUCT34  108633.229299  117445.576337  108633.229299  117445.576337
         PRODUCT4    25851.547771   32905.547789   25851.547771   32905.547789
         PRODUCT47   10998.159236    8243.442040   10998.159236    8243.442040
         PRODUCT56    6296.229299    1832.616295    6296.229299    1832.616295
         PRODUCT57    6804.643312    1391.225843    6804.643312    1391.225843
         PRODUCT58   27346.216561   28091.461510   27346.216561   28091.461510
         PRODUCT59  642760.585987  180794.220476  642760.585987  180794.220476
         PRODUCT6      800.222930    3261.663137     807.745223    3259.556767
         PRODUCT60       0.636943       2.295907       0.923567       2.058570
         PRODUCT62   11378.993631    5731.819330   11378.993631    5731.819330
         PRODUCT63   47715.101911   34580.487660   47715.101911   34580.487660
         PRODUCT7     2080.101911    1302.436879    2080.101911    1302.436879
         PRODUCT75   30013.961783    9336.409864   30013.961783    9336.409864
         PRODUCT8      186.719745     160.538710     186.719745     160.538710
A02      PRODUCT1      155.331210     146.356580     155.331210     146.356580
         PRODUCT12    8995.910828    7315.563434    8995.910828    7315.563434
         PRODUCT14    1797.044586     685.720754    1797.044586     685.720754
         PRODUCT16      23.509554      57.139350      23.528662      57.131154
...                           ...            ...            ...            ...
A65      PRODUCT1       62.388535      41.711563      62.388535      41.711563
         PRODUCT12    1114.828025     652.368880    1114.828025     652.368880
         PRODUCT14      16.834395      15.913970      16.847134      15.899591
         PRODUCT33     122.942675      55.760390     122.942675      55.760390
         PRODUCT34    1780.127389    1524.126348    1780.127389    1524.126348
         PRODUCT40       9.554140      10.209595       9.554140      10.209595
         PRODUCT47      23.089172      20.011656      23.089172      20.011656
         PRODUCT56      88.203822      28.963226      88.203822      28.963226
         PRODUCT57      91.165605      39.983947      91.165605      39.983947
         PRODUCT58     181.369427     197.959860     181.369427     197.959860
         PRODUCT59   12114.452229    5817.423758   12114.452229    5817.423758
         PRODUCT60      82.159236      25.452195      82.159236      25.452195
         PRODUCT62     187.605096      56.698229     187.605096      56.698229
A66      PRODUCT34     176.936306     281.946523     176.936306     281.946523
         PRODUCT58       4.789809       8.564261       4.789809       8.564261
         PRODUCT59    3788.566879    2205.732553    3788.566879    2205.732553
A67      PRODUCT34     703.484076     349.442589     703.484076     349.442589
         PRODUCT58      40.796178      62.086141      40.796178      62.086141
         PRODUCT59   21489.286624    6434.134741   21489.286624    6434.134741
A68      PRODUCT34     290.184713     179.060469     290.184713     179.060469
         PRODUCT58       1.649682       4.251495       1.649682       4.251495
         PRODUCT59    7785.178344    5578.579027    7785.178344    5578.579027
A69      PRODUCT34     166.184713     203.227289     166.184713     203.227289
         PRODUCT58       4.611465       5.921116       4.611465       5.921116
         PRODUCT59    8320.515924    6085.234172    8320.515924    6085.234172
A70      PRODUCT34    2165.585987    1479.518945    2165.585987    1479.518945
         PRODUCT58      61.496815      67.393280      61.496815      67.393280
         PRODUCT59   69471.617834   35908.174284   69471.617834   35908.174284
A77      PRODUCT1     2890.745223     940.912186    2890.745223     940.912186
         PRODUCT12    3473.324841    1687.580677    3473.324841    1687.580677

[794 rows x 4 columns]

In [35]:
groupDataSize = sortedData.groupby(["REGIONID" , "PRODUCT" ])["QTY", "new_QTY"].agg(["size"])

In [36]:
groupData.rename(columns = {"QTY":"MEAN", "new_QTY":"STD"} , inplace = True)

In [37]:
joinKey = ["REGIONID", "PRODUCT"]

In [38]:
joinData = pd.merge(sortedData, groupData, left_on = joinKey, right_on = joinKey)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

In [39]:
joinData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,new_QTY,YAER,WEEK,"(MEAN, mean)","(MEAN, std)","(STD, mean)","(STD, std)"
0,A00,PRODUCT34,201401,661.0,661.0,2014,01,132.44586,154.867743,132.44586,154.867743
1,A00,PRODUCT34,201402,679.0,679.0,2014,02,132.44586,154.867743,132.44586,154.867743
2,A00,PRODUCT34,201403,578.0,578.0,2014,03,132.44586,154.867743,132.44586,154.867743
3,A00,PRODUCT34,201404,532.0,532.0,2014,04,132.44586,154.867743,132.44586,154.867743
4,A00,PRODUCT34,201405,516.0,516.0,2014,05,132.44586,154.867743,132.44586,154.867743

In [40]:
groupDataMean = sortedData.groupby(groupKey).agg("mean")

In [41]:
groupDataMean.rename(columns = {"new_QTY":"QTY_MEAN"}, inplace = True)

In [42]:
mergedData = pd.merge(sortedData, groupDataMean, left_on = joinKey, right_on = joinKey)

In [43]:
mergedData = mergedData[["REGIONID", "PRODUCT", "WEEK","QTY_MEAN"]]

In [44]:
mergedData.head()

  REGIONID    PRODUCT WEEK   QTY_MEAN
0      A00  PRODUCT34   01  132.44586
1      A00  PRODUCT34   02  132.44586
2      A00  PRODUCT34   03  132.44586
3      A00  PRODUCT34   04  132.44586
4      A00  PRODUCT34   05  132.44586

In [45]:
mergedData.rename(columns = {"QTY_MEAN":"SEASONALITY"}, inplace = True)

In [46]:
mergedData.head()

  REGIONID    PRODUCT WEEK  SEASONALITY
0      A00  PRODUCT34   01    132.44586
1      A00  PRODUCT34   02    132.44586
2      A00  PRODUCT34   03    132.44586
3      A00  PRODUCT34   04    132.44586
4      A00  PRODUCT34   05    132.44586

### seasonMap_ 조회하려고 하나봐

In [47]:
seasonMap = mergedData.groupby(["REGIONID","PRODUCT","WEEK"])["SEASONALITY"].agg("mean").to_dict()

In [61]:
seasonMap

{('A00', 'PRODUCT34', '01'): 132.44585987261146,
 ('A00', 'PRODUCT34', '02'): 132.44585987261146,
 ('A00', 'PRODUCT34', '03'): 132.44585987261146,
 ('A00', 'PRODUCT34', '04'): 132.44585987261146,
 ('A00', 'PRODUCT34', '05'): 132.44585987261146,
 ('A00', 'PRODUCT34', '06'): 132.44585987261146,
 ('A00', 'PRODUCT34', '07'): 132.44585987261146,
 ('A00', 'PRODUCT34', '08'): 132.44585987261146,
 ('A00', 'PRODUCT34', '09'): 132.44585987261146,
 ('A00', 'PRODUCT34', '10'): 132.44585987261146,
 ('A00', 'PRODUCT34', '11'): 132.44585987261146,
 ('A00', 'PRODUCT34', '12'): 132.44585987261146,
 ('A00', 'PRODUCT34', '13'): 132.44585987261146,
 ('A00', 'PRODUCT34', '14'): 132.44585987261146,
 ('A00', 'PRODUCT34', '15'): 132.44585987261146,
 ('A00', 'PRODUCT34', '16'): 132.44585987261146,
 ('A00', 'PRODUCT34', '17'): 132.44585987261146,
 ('A00', 'PRODUCT34', '18'): 132.44585987261146,
 ('A00', 'PRODUCT34', '19'): 132.44585987261146,
 ('A00', 'PRODUCT34', '20'): 132.44585987261146,
 ('A00', 'PRODUCT34', '21'): 132.44585987261146,
 ('A00', 'PRODUCT34', '22'): 132.44585987261146,
 ('A00', 'PRODUCT34', '23'): 132.44585987261146,
 ('A00', 'PRODUCT34', '24'): 132.44585987261146,
 ('A00', 'PRODUCT34', '25'): 132.44585987261146,
 ('A00', 'PRODUCT34', '26'): 132.44585987261146,
 ('A00', 'PRODUCT34', '27'): 132.44585987261146,
 ('A00', 'PRODUCT34', '28'): 132.44585987261146,
 ('A00', 'PRODUCT34', '29'): 132.44585987261146,
 ('A00', 'PRODUCT34', '30'): 132.44585987261146,
 ('A00', 'PRODUCT34', '31'): 132.44585987261146,
 ('A00', 'PRODUCT34', '32'): 132.44585987261146,
 ('A00', 'PRODUCT34', '33'): 132.44585987261146,
 ('A00', 'PRODUCT34', '34'): 132.44585987261146,
 ('A00', 'PRODUCT34', '35'): 132.44585987261146,
 ('A00', 'PRODUCT34', '36'): 132.44585987261146,
 ('A00', 'PRODUCT34', '37'): 132.44585987261146,
 ('A00', 'PRODUCT34', '38'): 132.44585987261146,
 ('A00', 'PRODUCT34', '39'): 132.44585987261146,
 ('A00', 'PRODUCT34', '40'): 132.44585987261146,
 ('A00', 'PRODUCT34', '41'): 132.44585987261146,
 ('A00', 'PRODUCT34', '42'): 132.44585987261146,
 ('A00', 'PRODUCT34', '43'): 132.44585987261146,
 ('A00', 'PRODUCT34', '44'): 132.44585987261146,
 ('A00', 'PRODUCT34', '45'): 132.44585987261146,
 ('A00', 'PRODUCT34', '46'): 132.44585987261146,
 ('A00', 'PRODUCT34', '47'): 132.44585987261146,
 ('A00', 'PRODUCT34', '48'): 132.44585987261146,
 ('A00', 'PRODUCT34', '49'): 132.44585987261146,
 ('A00', 'PRODUCT34', '50'): 132.44585987261146,
 ('A00', 'PRODUCT34', '51'): 132.44585987261146,
 ('A00', 'PRODUCT34', '52'): 132.44585987261146,
 ('A00', 'PRODUCT34', '53'): 132.44585987261146,
 ('A00', 'PRODUCT58', '01'): 105.23566878980891,
 ('A00', 'PRODUCT58', '02'): 105.23566878980891,
 ('A00', 'PRODUCT58', '03'): 105.23566878980891,
 ('A00', 'PRODUCT58', '04'): 105.23566878980891,
 ('A00', 'PRODUCT58', '05'): 105.23566878980891,
 ('A00', 'PRODUCT58', '06'): 105.23566878980891,
 ('A00', 'PRODUCT58', '07'): 105.23566878980891,
 ('A00', 'PRODUCT58', '08'): 105.23566878980891,
 ('A00', 'PRODUCT58', '09'): 105.23566878980891,
 ('A00', 'PRODUCT58', '10'): 105.23566878980891,
 ('A00', 'PRODUCT58', '11'): 105.23566878980891,
 ('A00', 'PRODUCT58', '12'): 105.23566878980891,
 ('A00', 'PRODUCT58', '13'): 105.23566878980891,
 ('A00', 'PRODUCT58', '14'): 105.23566878980891,
 ('A00', 'PRODUCT58', '15'): 105.23566878980891,
 ('A00', 'PRODUCT58', '16'): 105.23566878980891,
 ('A00', 'PRODUCT58', '17'): 105.23566878980891,
 ('A00', 'PRODUCT58', '18'): 105.23566878980891,
 ('A00', 'PRODUCT58', '19'): 105.23566878980891,
 ('A00', 'PRODUCT58', '20'): 105.23566878980891,
 ('A00', 'PRODUCT58', '21'): 105.23566878980891,
 ('A00', 'PRODUCT58', '22'): 105.23566878980891,
 ('A00', 'PRODUCT58', '23'): 105.23566878980891,
 ('A00', 'PRODUCT58', '24'): 105.23566878980891,
 ('A00', 'PRODUCT58', '25'): 105.23566878980891,
 ('A00', 'PRODUCT58', '26'): 105.23566878980891,
 ('A00', 'PRODUCT58', '27'): 105.23566878980891,
 ('A00', 'PRODUCT58', '28'): 105.23566878980891,
 ('A00', 'PRODUCT58', '29'): 105.23566878980891,
 ('A00', 'PRODUCT58', '30'): 105.23566878980891,
 ('A00', 'PRODUCT58', '31'): 105.23566878980891,
 ('A00', 'PRODUCT58', '32'): 105.23566878980891,
 ('A00', 'PRODUCT58', '33'): 105.23566878980891,
 ('A00', 'PRODUCT58', '34'): 105.23566878980891,
 ('A00', 'PRODUCT58', '35'): 105.23566878980891,
 ('A00', 'PRODUCT58', '36'): 105.23566878980891,
 ('A00', 'PRODUCT58', '37'): 105.23566878980891,
 ('A00', 'PRODUCT58', '38'): 105.23566878980891,
 ('A00', 'PRODUCT58', '39'): 105.23566878980891,
 ('A00', 'PRODUCT58', '40'): 105.23566878980891,
 ('A00', 'PRODUCT58', '41'): 105.23566878980891,
 ('A00', 'PRODUCT58', '42'): 105.23566878980891,
 ('A00', 'PRODUCT58', '43'): 105.23566878980891,
 ('A00', 'PRODUCT58', '44'): 105.23566878980891,
 ('A00', 'PRODUCT58', '45'): 105.23566878980891,
 ('A00', 'PRODUCT58', '46'): 105.23566878980891,
 ('A00', 'PRODUCT58', '47'): 105.23566878980891,
 ('A00', 'PRODUCT58', '48'): 105.23566878980891,
 ('A00', 'PRODUCT58', '49'): 105.23566878980891,
 ('A00', 'PRODUCT58', '50'): 105.23566878980891,
 ('A00', 'PRODUCT58', '51'): 105.23566878980891,
 ('A00', 'PRODUCT58', '52'): 105.23566878980891,
 ('A00', 'PRODUCT58', '53'): 105.23566878980891,
 ('A00', 'PRODUCT59', '01'): 36086.547770700636,
 ('A00', 'PRODUCT59', '02'): 36086.547770700636,
 ('A00', 'PRODUCT59', '03'): 36086.547770700636,
 ('A00', 'PRODUCT59', '04'): 36086.547770700636,
 ('A00', 'PRODUCT59', '05'): 36086.547770700636,
 ('A00', 'PRODUCT59', '06'): 36086.547770700636,
 ('A00', 'PRODUCT59', '07'): 36086.547770700636,
 ('A00', 'PRODUCT59', '08'): 36086.547770700636,
 ('A00', 'PRODUCT59', '09'): 36086.547770700636,
 ('A00', 'PRODUCT59', '10'): 36086.547770700636,
 ('A00', 'PRODUCT59', '11'): 36086.547770700636,
 ('A00', 'PRODUCT59', '12'): 36086.547770700636,
 ('A00', 'PRODUCT59', '13'): 36086.547770700636,
 ('A00', 'PRODUCT59', '14'): 36086.547770700636,
 ('A00', 'PRODUCT59', '15'): 36086.547770700636,
 ('A00', 'PRODUCT59', '16'): 36086.547770700636,
 ('A00', 'PRODUCT59', '17'): 36086.547770700636,
 ('A00', 'PRODUCT59', '18'): 36086.547770700636,
 ('A00', 'PRODUCT59', '19'): 36086.547770700636,
 ('A00', 'PRODUCT59', '20'): 36086.547770700636,
 ('A00', 'PRODUCT59', '21'): 36086.547770700636,
 ('A00', 'PRODUCT59', '22'): 36086.547770700636,
 ('A00', 'PRODUCT59', '23'): 36086.547770700636,
 ('A00', 'PRODUCT59', '24'): 36086.547770700636,
 ('A00', 'PRODUCT59', '25'): 36086.547770700636,
 ('A00', 'PRODUCT59', '26'): 36086.547770700636,
 ('A00', 'PRODUCT59', '27'): 36086.547770700636,
 ('A00', 'PRODUCT59', '28'): 36086.547770700636,
 ('A00', 'PRODUCT59', '29'): 36086.547770700636,
 ('A00', 'PRODUCT59', '30'): 36086.547770700636,
 ('A00', 'PRODUCT59', '31'): 36086.547770700636,
 ('A00', 'PRODUCT59', '32'): 36086.547770700636,
 ('A00', 'PRODUCT59', '33'): 36086.547770700636,
 ('A00', 'PRODUCT59', '34'): 36086.547770700636,
 ('A00', 'PRODUCT59', '35'): 36086.547770700636,
 ('A00', 'PRODUCT59', '36'): 36086.547770700636,
 ('A00', 'PRODUCT59', '37'): 36086.547770700636,
 ('A00', 'PRODUCT59', '38'): 36086.547770700636,
 ('A00', 'PRODUCT59', '39'): 36086.547770700636,
 ('A00', 'PRODUCT59', '40'): 36086.547770700636,
 ('A00', 'PRODUCT59', '41'): 36086.547770700636,
 ('A00', 'PRODUCT59', '42'): 36086.547770700636,
 ('A00', 'PRODUCT59', '43'): 36086.547770700636,
 ('A00', 'PRODUCT59', '44'): 36086.547770700636,
 ('A00', 'PRODUCT59', '45'): 36086.547770700636,
 ('A00', 'PRODUCT59', '46'): 36086.547770700636,
 ('A00', 'PRODUCT59', '47'): 36086.547770700636,
 ('A00', 'PRODUCT59', '48'): 36086.547770700636,
 ('A00', 'PRODUCT59', '49'): 36086.547770700636,
 ('A00', 'PRODUCT59', '50'): 36086.547770700636,
 ('A00', 'PRODUCT59', '51'): 36086.547770700636,
 ('A00', 'PRODUCT59', '52'): 36086.547770700636,
 ('A00', 'PRODUCT59', '53'): 36086.547770700636,
 ('A01', 'PRODUCT1', '01'): 5716.726114649681,
 ('A01', 'PRODUCT1', '02'): 5716.726114649681,
 ('A01', 'PRODUCT1', '03'): 5716.726114649681,
 ('A01', 'PRODUCT1', '04'): 5716.726114649681,
 ('A01', 'PRODUCT1', '05'): 5716.726114649681,
 ('A01', 'PRODUCT1', '06'): 5716.726114649681,
 ('A01', 'PRODUCT1', '07'): 5716.726114649681,
 ('A01', 'PRODUCT1', '08'): 5716.726114649681,
 ('A01', 'PRODUCT1', '09'): 5716.726114649681,
 ('A01', 'PRODUCT1', '10'): 5716.726114649681,
 ('A01', 'PRODUCT1', '11'): 5716.726114649681,
 ('A01', 'PRODUCT1', '12'): 5716.726114649681,
 ('A01', 'PRODUCT1', '13'): 5716.726114649681,
 ('A01', 'PRODUCT1', '14'): 5716.726114649681,
 ('A01', 'PRODUCT1', '15'): 5716.726114649681,
 ('A01', 'PRODUCT1', '16'): 5716.726114649681,
 ('A01', 'PRODUCT1', '17'): 5716.726114649681,
 ('A01', 'PRODUCT1', '18'): 5716.726114649681,
 ('A01', 'PRODUCT1', '19'): 5716.726114649681,
 ('A01', 'PRODUCT1', '20'): 5716.726114649681,
 ('A01', 'PRODUCT1', '21'): 5716.726114649681,
 ('A01', 'PRODUCT1', '22'): 5716.726114649681,
 ('A01', 'PRODUCT1', '23'): 5716.726114649681,
 ('A01', 'PRODUCT1', '24'): 5716.726114649681,
 ('A01', 'PRODUCT1', '25'): 5716.726114649681,
 ('A01', 'PRODUCT1', '26'): 5716.726114649681,
 ('A01', 'PRODUCT1', '27'): 5716.726114649681,
 ('A01', 'PRODUCT1', '28'): 5716.726114649681,
 ('A01', 'PRODUCT1', '29'): 5716.726114649681,
 ('A01', 'PRODUCT1', '30'): 5716.726114649681,
 ('A01', 'PRODUCT1', '31'): 5716.726114649681,
 ('A01', 'PRODUCT1', '32'): 5716.726114649681,
 ('A01', 'PRODUCT1', '33'): 5716.726114649681,
 ('A01', 'PRODUCT1', '34'): 5716.726114649681,
 ('A01', 'PRODUCT1', '35'): 5716.726114649681,
 ('A01', 'PRODUCT1', '36'): 5716.726114649681,
 ('A01', 'PRODUCT1', '37'): 5716.726114649681,
 ('A01', 'PRODUCT1', '38'): 5716.726114649681,
 ('A01', 'PRODUCT1', '39'): 5716.726114649681,
 ('A01', 'PRODUCT1', '40'): 5716.726114649681,
 ('A01', 'PRODUCT1', '41'): 5716.726114649681,
 ('A01', 'PRODUCT1', '42'): 5716.726114649681,
 ('A01', 'PRODUCT1', '43'): 5716.726114649681,
 ('A01', 'PRODUCT1', '44'): 5716.726114649681,
 ('A01', 'PRODUCT1', '45'): 5716.726114649681,
 ('A01', 'PRODUCT1', '46'): 5716.726114649681,
 ('A01', 'PRODUCT1', '47'): 5716.726114649681,
 ('A01', 'PRODUCT1', '48'): 5716.726114649681,
 ('A01', 'PRODUCT1', '49'): 5716.726114649681,
 ('A01', 'PRODUCT1', '50'): 5716.726114649681,
 ('A01', 'PRODUCT1', '51'): 5716.726114649681,
 ('A01', 'PRODUCT1', '52'): 5716.726114649681,
 ('A01', 'PRODUCT1', '53'): 5716.726114649681,
 ('A01', 'PRODUCT12', '01'): 197052.77707006372,
 ('A01', 'PRODUCT12', '02'): 197052.77707006372,
 ('A01', 'PRODUCT12', '03'): 197052.77707006372,
 ('A01', 'PRODUCT12', '04'): 197052.77707006372,
 ('A01', 'PRODUCT12', '05'): 197052.77707006372,
 ('A01', 'PRODUCT12', '06'): 197052.77707006372,
 ('A01', 'PRODUCT12', '07'): 197052.77707006372,
 ('A01', 'PRODUCT12', '08'): 197052.77707006372,
 ('A01', 'PRODUCT12', '09'): 197052.77707006372,
 ('A01', 'PRODUCT12', '10'): 197052.77707006372,
 ('A01', 'PRODUCT12', '11'): 197052.77707006372,
 ('A01', 'PRODUCT12', '12'): 197052.77707006372,
 ('A01', 'PRODUCT12', '13'): 197052.77707006372,
 ('A01', 'PRODUCT12', '14'): 197052.77707006372,
 ('A01', 'PRODUCT12', '15'): 197052.77707006372,
 ('A01', 'PRODUCT12', '16'): 197052.77707006372,
 ('A01', 'PRODUCT12', '17'): 197052.77707006372,
 ('A01', 'PRODUCT12', '18'): 197052.77707006372,
 ('A01', 'PRODUCT12', '19'): 197052.77707006372,
 ('A01', 'PRODUCT12', '20'): 197052.77707006372,
 ('A01', 'PRODUCT12', '21'): 197052.77707006372,
 ('A01', 'PRODUCT12', '22'): 197052.77707006372,
 ('A01', 'PRODUCT12', '23'): 197052.77707006372,
 ('A01', 'PRODUCT12', '24'): 197052.77707006372,
 ('A01', 'PRODUCT12', '25'): 197052.77707006372,
 ('A01', 'PRODUCT12', '26'): 197052.77707006372,
 ('A01', 'PRODUCT12', '27'): 197052.77707006372,
 ('A01', 'PRODUCT12', '28'): 197052.77707006372,
 ('A01', 'PRODUCT12', '29'): 197052.77707006372,
 ('A01', 'PRODUCT12', '30'): 197052.77707006372,
 ('A01', 'PRODUCT12', '31'): 197052.77707006372,
 ('A01', 'PRODUCT12', '32'): 197052.77707006372,
 ('A01', 'PRODUCT12', '33'): 197052.77707006372,
 ('A01', 'PRODUCT12', '34'): 197052.77707006372,
 ('A01', 'PRODUCT12', '35'): 197052.77707006372,
 ('A01', 'PRODUCT12', '36'): 197052.77707006372,
 ('A01', 'PRODUCT12', '37'): 197052.77707006372,
 ('A01', 'PRODUCT12', '38'): 197052.77707006372,
 ('A01', 'PRODUCT12', '39'): 197052.77707006372,
 ('A01', 'PRODUCT12', '40'): 197052.77707006372,
 ('A01', 'PRODUCT12', '41'): 197052.77707006372,
 ('A01', 'PRODUCT12', '42'): 197052.77707006372,
 ('A01', 'PRODUCT12', '43'): 197052.77707006372,
 ('A01', 'PRODUCT12', '44'): 197052.77707006372,
 ('A01', 'PRODUCT12', '45'): 197052.77707006372,
 ('A01', 'PRODUCT12', '46'): 197052.77707006372,
 ('A01', 'PRODUCT12', '47'): 197052.77707006372,
 ('A01', 'PRODUCT12', '48'): 197052.77707006372,
 ('A01', 'PRODUCT12', '49'): 197052.77707006372,
 ('A01', 'PRODUCT12', '50'): 197052.77707006372,
 ('A01', 'PRODUCT12', '51'): 197052.77707006372,
 ('A01', 'PRODUCT12', '52'): 197052.77707006372,
 ('A01', 'PRODUCT12', '53'): 197052.7770700637,
 ('A01', 'PRODUCT14', '01'): 17934.738853503186,
 ('A01', 'PRODUCT14', '02'): 17934.738853503186,
 ('A01', 'PRODUCT14', '03'): 17934.738853503186,
 ('A01', 'PRODUCT14', '04'): 17934.738853503186,
 ('A01', 'PRODUCT14', '05'): 17934.738853503186,
 ('A01', 'PRODUCT14', '06'): 17934.738853503186,
 ('A01', 'PRODUCT14', '07'): 17934.738853503186,
 ('A01', 'PRODUCT14', '08'): 17934.738853503186,
 ('A01', 'PRODUCT14', '09'): 17934.738853503186,
 ('A01', 'PRODUCT14', '10'): 17934.738853503186,
 ('A01', 'PRODUCT14', '11'): 17934.738853503186,
 ('A01', 'PRODUCT14', '12'): 17934.738853503186,
 ('A01', 'PRODUCT14', '13'): 17934.738853503186,
 ('A01', 'PRODUCT14', '14'): 17934.738853503186,
 ('A01', 'PRODUCT14', '15'): 17934.738853503186,
 ('A01', 'PRODUCT14', '16'): 17934.738853503186,
 ('A01', 'PRODUCT14', '17'): 17934.738853503186,
 ('A01', 'PRODUCT14', '18'): 17934.738853503186,
 ('A01', 'PRODUCT14', '19'): 17934.738853503186,
 ('A01', 'PRODUCT14', '20'): 17934.738853503186,
 ('A01', 'PRODUCT14', '21'): 17934.738853503186,
 ('A01', 'PRODUCT14', '22'): 17934.738853503186,
 ('A01', 'PRODUCT14', '23'): 17934.738853503186,
 ('A01', 'PRODUCT14', '24'): 17934.738853503186,
 ('A01', 'PRODUCT14', '25'): 17934.738853503186,
 ('A01', 'PRODUCT14', '26'): 17934.738853503186,
 ('A01', 'PRODUCT14', '27'): 17934.738853503186,
 ('A01', 'PRODUCT14', '28'): 17934.738853503186,
 ('A01', 'PRODUCT14', '29'): 17934.738853503186,
 ('A01', 'PRODUCT14', '30'): 17934.738853503186,
 ('A01', 'PRODUCT14', '31'): 17934.738853503186,
 ('A01', 'PRODUCT14', '32'): 17934.738853503186,
 ('A01', 'PRODUCT14', '33'): 17934.738853503186,
 ('A01', 'PRODUCT14', '34'): 17934.738853503186,
 ('A01', 'PRODUCT14', '35'): 17934.738853503186,
 ('A01', 'PRODUCT14', '36'): 17934.738853503186,
 ('A01', 'PRODUCT14', '37'): 17934.738853503186,
 ('A01', 'PRODUCT14', '38'): 17934.738853503186,
 ('A01', 'PRODUCT14', '39'): 17934.738853503186,
 ('A01', 'PRODUCT14', '40'): 17934.738853503186,
 ('A01', 'PRODUCT14', '41'): 17934.738853503186,
 ('A01', 'PRODUCT14', '42'): 17934.738853503186,
 ('A01', 'PRODUCT14', '43'): 17934.738853503186,
 ('A01', 'PRODUCT14', '44'): 17934.738853503186,
 ('A01', 'PRODUCT14', '45'): 17934.738853503186,
 ('A01', 'PRODUCT14', '46'): 17934.738853503186,
 ('A01', 'PRODUCT14', '47'): 17934.738853503186,
 ('A01', 'PRODUCT14', '48'): 17934.738853503186,
 ('A01', 'PRODUCT14', '49'): 17934.738853503186,
 ('A01', 'PRODUCT14', '50'): 17934.738853503186,
 ('A01', 'PRODUCT14', '51'): 17934.738853503186,
 ('A01', 'PRODUCT14', '52'): 17934.738853503186,
 ('A01', 'PRODUCT14', '53'): 17934.738853503186,
 ('A01', 'PRODUCT15', '01'): 4759.554140127389,
 ('A01', 'PRODUCT15', '02'): 4759.554140127389,
 ('A01', 'PRODUCT15', '03'): 4759.554140127389,
 ('A01', 'PRODUCT15', '04'): 4759.554140127389,
 ('A01', 'PRODUCT15', '05'): 4759.554140127389,
 ('A01', 'PRODUCT15', '06'): 4759.554140127389,
 ('A01', 'PRODUCT15', '07'): 4759.554140127389,
 ('A01', 'PRODUCT15', '08'): 4759.554140127389,
 ('A01', 'PRODUCT15', '09'): 4759.554140127389,
 ('A01', 'PRODUCT15', '10'): 4759.554140127389,
 ('A01', 'PRODUCT15', '11'): 4759.554140127389,
 ('A01', 'PRODUCT15', '12'): 4759.554140127389,
 ('A01', 'PRODUCT15', '13'): 4759.554140127389,
 ('A01', 'PRODUCT15', '14'): 4759.554140127389,
 ('A01', 'PRODUCT15', '15'): 4759.554140127389,
 ('A01', 'PRODUCT15', '16'): 4759.554140127389,
 ('A01', 'PRODUCT15', '17'): 4759.554140127389,
 ('A01', 'PRODUCT15', '18'): 4759.554140127389,
 ('A01', 'PRODUCT15', '19'): 4759.554140127389,
 ('A01', 'PRODUCT15', '20'): 4759.554140127389,
 ('A01', 'PRODUCT15', '21'): 4759.554140127389,
 ('A01', 'PRODUCT15', '22'): 4759.554140127389,
 ('A01', 'PRODUCT15', '23'): 4759.554140127389,
 ('A01', 'PRODUCT15', '24'): 4759.554140127389,
 ('A01', 'PRODUCT15', '25'): 4759.554140127389,
 ('A01', 'PRODUCT15', '26'): 4759.554140127389,
 ('A01', 'PRODUCT15', '27'): 4759.554140127389,
 ('A01', 'PRODUCT15', '28'): 4759.554140127389,
 ('A01', 'PRODUCT15', '29'): 4759.554140127389,
 ('A01', 'PRODUCT15', '30'): 4759.554140127389,
 ('A01', 'PRODUCT15', '31'): 4759.554140127389,
 ('A01', 'PRODUCT15', '32'): 4759.554140127389,
 ('A01', 'PRODUCT15', '33'): 4759.554140127389,
 ('A01', 'PRODUCT15', '34'): 4759.554140127389,
 ('A01', 'PRODUCT15', '35'): 4759.554140127389,
 ('A01', 'PRODUCT15', '36'): 4759.554140127389,
 ('A01', 'PRODUCT15', '37'): 4759.554140127389,
 ('A01', 'PRODUCT15', '38'): 4759.554140127389,
 ('A01', 'PRODUCT15', '39'): 4759.554140127389,
 ('A01', 'PRODUCT15', '40'): 4759.554140127389,
 ('A01', 'PRODUCT15', '41'): 4759.554140127389,
 ('A01', 'PRODUCT15', '42'): 4759.554140127389,
 ('A01', 'PRODUCT15', '43'): 4759.554140127389,
 ('A01', 'PRODUCT15', '44'): 4759.554140127389,
 ('A01', 'PRODUCT15', '45'): 4759.554140127389,
 ('A01', 'PRODUCT15', '46'): 4759.554140127389,
 ('A01', 'PRODUCT15', '47'): 4759.554140127389,
 ('A01', 'PRODUCT15', '48'): 4759.554140127389,
 ('A01', 'PRODUCT15', '49'): 4759.554140127389,
 ('A01', 'PRODUCT15', '50'): 4759.554140127389,
 ('A01', 'PRODUCT15', '51'): 4759.554140127389,
 ('A01', 'PRODUCT15', '52'): 4759.554140127389,
 ('A01', 'PRODUCT15', '53'): 4759.554140127389,
 ('A01', 'PRODUCT16', '01'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '02'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '03'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '04'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '05'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '06'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '07'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '08'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '09'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '10'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '11'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '12'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '13'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '14'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '15'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '16'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '17'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '18'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '19'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '20'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '21'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '22'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '23'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '24'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '25'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '26'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '27'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '28'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '29'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '30'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '31'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '32'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '33'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '34'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '35'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '36'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '37'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '38'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '39'): 1392.3949044585988,
 ('A01', 'PRODUCT16', '40'): 1392.3949044585988,

In [48]:
##spark 처럼 조회를 하는 것 같은데, 다시 봐야겠다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ---> 맞다
selectKey = ("A00","PRODUCT34","01")
if selectKey in seasonMap:
    selectResult = seasonMap[selectKey]
else:
    selectResult = None
print(selectResult)

132.44585987261146

In [62]:
emptyColumns = ["REGIONID","PRODUCT","ITEM","YEARWEEK","QTY"]
emptydf = pd.DataFrame(columns = emptyColumns)

In [63]:
REGIONID = "A00"
PRODUCT = "PRODUCT34"
ITEM = "ITEM01"
STARTWEEK = "201925"

In [64]:
PAST_WINDOW = 4

In [65]:
#함수 쓰게 라이브러리 하나 넣고
from fintechlab import CommonFunction as cf

In [66]:
for i in range(0, PAST_WINDOW):
    emptydf = emptydf.append(pd.DataFrame([[REGIONID, PRODUCT, ITEM, cf.preWeek(STARTWEEK, i ),100+(i*10)]] , columns = emptyColumns) , ignore_index = True  ) #i 가 for 문 돌면서 preWeek 내에서 다른 주 로 컬럼 만들어져

In [67]:
emptydf

  REGIONID    PRODUCT    ITEM YEARWEEK  QTY
0      A00  PRODUCT34  ITEM01   201925  100
1      A00  PRODUCT34  ITEM01   201924  110
2      A00  PRODUCT34  ITEM01   201923  120
3      A00  PRODUCT34  ITEM01   201922  130

In [69]:
stdQty = emptydf.QTY.mean()
stdQty

115.0

In [71]:
weekList = emptydf.YEARWEEK.str[4:6]
seasonList = []
for i in weekList:
    seasonList.append(seasonMap[REGIONID,PRODUCT,i])

In [72]:
seasonList

[132.44585987261146,
 132.44585987261146,
 132.44585987261146,
 132.44585987261146]

## 정렬

In [49]:
groupKey2 = ["REGIONID","PRODUCT"]

In [50]:
groupData2 = sortedData.groupby(groupKey2)

In [51]:
len(groupData2)

794

In [52]:
#drop_duplicates 는 쿼리에서 distinct 랑 같아 _ 같은 자료 없애주나봐
len(sortedData[["REGIONID","PRODUCT"]].drop_duplicates())

794

In [53]:
#groupData 에서 하나를 뽑아서 디버깅?
#groupData2 의 여러 그룹들 중에서 하나를 가져오겠다
oneGroup = groupData2.get_group(list(groupData2.groups)[0])

In [54]:
len(oneGroup)

157

In [55]:
#한줄씩 작성하고 나서 함수화
def mafunction(oneGroup , in_window):
    eachData = oneGroup.reset_index(drop = True)
    eachData.head()
    
    eachData["MA"] = eachData.new_QTY.rolling(window= in_window, center = True, min_periods = 1 ).mean()
    
    return eachData

In [56]:
WINDOW = 5

In [57]:
groupData2 = sortedData.groupby(groupKey2).apply(mafunction, (WINDOW))

In [58]:
groupData2.head()

                     REGIONID    PRODUCT YEARWEEK    QTY  new_QTY  YAER WEEK  \
REGIONID PRODUCT
A00      PRODUCT34 0      A00  PRODUCT34   201401  661.0    661.0  2014   01
                   1      A00  PRODUCT34   201402  679.0    679.0  2014   02
                   2      A00  PRODUCT34   201403  578.0    578.0  2014   03
                   3      A00  PRODUCT34   201404  532.0    532.0  2014   04
                   4      A00  PRODUCT34   201405  516.0    516.0  2014   05

                              MA
REGIONID PRODUCT
A00      PRODUCT34 0  639.333333
                   1  612.500000
                   2  593.200000
                   3  545.600000
                   4  491.200000